numbers = [4, 5, 8, 12, 56]
numbers.append(100)
print(numbers)
numbers.insert(0,5)
print(numbers)
numbers.remove(5)
print(numbers)
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
print(numbers2)
numbers.clear()
print(numbers)